#!/bin/bash

# Generate the small core
./gen_alf -c arch=small       core.cmd > small_core.alf
./gen_alf -c arch=small -t 80 core.cmd > small_core_80.alf

# Generate the medium core
./gen_alf       core.cmd > medium_core.alf
./gen_alf -t 80 core.cmd > medium_core_80.alf

# Generate the big core
./gen_alf       core.cmd > big_core.alf
./gen_alf -t 80 core.cmd > big_core_80.alf
