on:
  pull_request:
    branches:
      - master

env:
  CACHE_VERSION: v1

name: Regress Olympia on Ubuntu
  build_test_job:
    strategy:
      # Strategy is a matrix of debug and release builds/regression
      matrix:
        os: [ubuntu-latest]
        BUILD_TYPE: [debug, release]

    name: Ubuntu-${{ matrix.BUILD_TYPE }}
    runs-on: ${{ matrix.os }}

  # Set up a global environment variable for build scripts
  env:
    OLYMPIA_BUILD_TYPE: ${{ matrix.BUILD_TYPE }}

  steps:
    - name: Checkout Sparta
      uses: actions/checkout@v2
        with:
          repository: sparcians/map
          path: map

    - name: Checkout Olympia
      uses: actions/checkout@v3
